apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: dual-container-app
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32080
