apiVersion: v1
kind: Pod
metadata:
  name: test-multitool-pod
  labels:
    app: test
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]
  restartPolicy: Never